OrdererOrgs:
  - Name: Orderer
    Domain: dummy.com
    Specs:
      - Hostname: orderer
    CA:
      OrganizationalUnit: admin
PeerOrgs:
  - Name: Org1
    Domain: org1.dummy.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.dummy.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.dummy.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
