version: '3.7'

networks:
  test:

services:
  orderer.dummy.com:
    container_name: orderer.dummy.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_PROFILE_ENABLED=true
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/dummy.com/orderers/orderer.dummy.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/dummy.com/orderers/orderer.dummy.com/tls/:/var/hyperledger/orderer/tls
    networks:
      - test

  couchdb.org1.dummy.com:
    image: couchdb:3.1.1
    container_name: couchdb.org1.dummy.com
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    ports:
      #  TO access the UI
      - 5984:5984
    networks:
      - test

  peer0.org1.dummy.com:
    image: hyperledger/fabric-peer:2.3
    container_name: peer0.org1.dummy.com
    depends_on: 
      - couchdb.org1.dummy.com
    environment:
      - DOCKER_NS=hyperledger
      - FABRIC_LOGGING_SPEC=info
      - TWO_DIGIT_VERSION=2.3
      - CORE_PEER_ID=peer0.org1.dummy.com
      - CORE_PEER_ADDRESS=peer0.org1.dummy.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.dummy.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.dummy.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/peer/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org1.dummy.com
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=${COMPOSE_PROJECT_NAME}_test
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org1.dummy.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=root
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=root
      # - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:2.3
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.dummy.com/peers/peer0.org1.dummy.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org1.dummy.com/peers/peer0.org1.dummy.com/tls:/var/hyperledger/peer/tls
    networks:
      - test

  peer0.org2.dummy.com:
    image: hyperledger/fabric-peer:2.3
    container_name: peer0.org2.dummy.com
    environment:
      - DOCKER_NS=hyperledger
      - FABRIC_LOGGING_SPEC=info
      - TWO_DIGIT_VERSION=2.3
      - CORE_PEER_ID=peer0.org2.dummy.com
      - CORE_PEER_ADDRESS=peer0.org2.dummy.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.dummy.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.dummy.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/peer/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org2.dummy.com
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=${COMPOSE_PROJECT_NAME}_test
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.dummy.com/peers/peer0.org2.dummy.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org2.dummy.com/peers/peer0.org2.dummy.com/tls:/var/hyperledger/peer/tls
    networks:
      - test

  peer0.org3.dummy.com:
    image: hyperledger/fabric-peer:2.3
    container_name: peer0.org3.dummy.com
    environment:
      - DOCKER_NS=hyperledger
      - FABRIC_LOGGING_SPEC=info
      - TWO_DIGIT_VERSION=2.3
      - CORE_PEER_ID=peer0.org3.dummy.com
      - CORE_PEER_ADDRESS=peer0.org3.dummy.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.dummy.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.dummy.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/peer/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org3.dummy.com
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=${COMPOSE_PROJECT_NAME}_test
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org3.dummy.com/peers/peer0.org3.dummy.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org3.dummy.com/peers/peer0.org3.dummy.com/tls:/var/hyperledger/peer/tls
    networks:
      - test
